#!/usr/bin/env bash
set -euo pipefail

LOCK_FILE="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")"/../.. && pwd)/versions.lock}"

detect_versions() {
  local semgrep joern zoekt
  semgrep=$(semgrep --version 2>/dev/null | head -n1 || echo "missing")
  joern=$(joern --version 2>/dev/null | head -n1 || echo "missing")
  zoekt=$(/Users/1004276/go/bin/zoekt --version 2>/dev/null | head -n1 || echo "missing")
  cat <<EOF
SEMREGP_VERSION=${semgrep}
JOERN_VERSION=${joern}
ZOEKT_VERSION=${zoekt}
EOF
}

if [[ ! -f "$LOCK_FILE" ]]; then
  echo "# autogenerated on $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >"$LOCK_FILE"
  detect_versions >>"$LOCK_FILE"
  echo "lock file created: $LOCK_FILE"
  exit 0
fi

fail=0
while IFS='=' read -r k v; do
  case "$k" in
    SEMREGP_VERSION) want_semgrep="$v" ;;
    JOERN_VERSION) want_joern="$v" ;;
    ZOEKT_VERSION) want_zoekt="$v" ;;
  esac
done <"$LOCK_FILE"

current_semgrep=$(semgrep --version 2>/dev/null | head -n1 || echo "missing")
current_joern=$(joern --version 2>/dev/null | head -n1 || echo "missing")
current_zoekt=$(/Users/1004276/go/bin/zoekt --version 2>/dev/null | head -n1 || echo "missing")

normalize() { echo "$1" | awk '{print $1}'; }
ns_semgrep=$(normalize "$current_semgrep"); nw_semgrep=$(normalize "${want_semgrep:-}")
ns_joern=$(normalize "$current_joern");   nw_joern=$(normalize "${want_joern:-}")
ns_zoekt=$(normalize "$current_zoekt");   nw_zoekt=$(normalize "${want_zoekt:-}")

if [[ -n "${want_semgrep:-}" && "$nw_semgrep" != "$ns_semgrep" ]]; then
  echo "ERROR: SEMREGP_VERSION expected '$want_semgrep' got '$current_semgrep'"
  fail=1
fi
if [[ -n "${want_joern:-}" && "$nw_joern" != "$ns_joern" ]]; then
  echo "ERROR: JOERN_VERSION expected '$want_joern' got '$current_joern'"
  fail=1
fi
if [[ -n "${want_zoekt:-}" && "$nw_zoekt" != "$ns_zoekt" ]]; then
  echo "ERROR: ZOEKT_VERSION expected '$want_zoekt' got '$current_zoekt'"
  fail=1
fi

if [[ $fail -ne 0 ]]; then
  echo "Version check failed. Update $LOCK_FILE intentionally if new versions are approved."
  exit 1
fi

echo "Version check OK."
