#!/usr/bin/env bash
# Run short HTTP fuzz for high-risk queue items.
# Inputs: fuzz_queue.json generated by high_risk_fuzz_gate.py
# Behavior: per-target time cap, overall time cap, writes coverage/log artifacts.
set -euo pipefail

usage() {
  cat <<EOF
Usage: $0 --queue <fuzz_queue.json> --state-dir <state> --run-id <run_id> [--base-url <url>] [--auth-token <token>] [--per-target-sec 600] [--max-total-sec 1800]
Notes:
  - This runner performs real HTTP requests via curl.
  - Set base URL using --base-url or FUZZ_BASE_URL.
EOF
}

QUEUE=""
STATE=""
RUN_ID=""
BASE_URL="${FUZZ_BASE_URL:-}"
AUTH_TOKEN="${FUZZ_AUTH_TOKEN:-}"
PER=600
TOTAL=1800
REQ_TIMEOUT=8

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0;;
    --queue) QUEUE="$2"; shift 2;;
    --state-dir) STATE="$2"; shift 2;;
    --run-id) RUN_ID="$2"; shift 2;;
    --base-url) BASE_URL="$2"; shift 2;;
    --auth-token) AUTH_TOKEN="$2"; shift 2;;
    --per-target-sec) PER="$2"; shift 2;;
    --max-total-sec) TOTAL="$2"; shift 2;;
    --request-timeout-sec) REQ_TIMEOUT="$2"; shift 2;;
    *) usage; exit 1;;
  esac
done

[[ -z "$QUEUE" || -z "$STATE" || -z "$RUN_ID" ]] && { usage; exit 1; }
if [[ -z "${BASE_URL}" ]]; then
  echo "run_fuzz_gate: missing base URL. Set --base-url or FUZZ_BASE_URL." >&2
  echo "run_fuzz_gate: no simulated fallback is used." >&2
  exit 2
fi

python - <<'PY' "$QUEUE" "$STATE" "$RUN_ID" "$PER" "$TOTAL" "$BASE_URL" "$AUTH_TOKEN" "$REQ_TIMEOUT"
import json
import os
import pathlib
import subprocess
import sys
import time
import uuid
import re

queue_path = pathlib.Path(sys.argv[1])
state_dir = pathlib.Path(sys.argv[2])
run_id = sys.argv[3]
per_target_sec = int(sys.argv[4])
max_total_sec = int(sys.argv[5])
base_url = sys.argv[6].rstrip("/")
auth_token = sys.argv[7]
req_timeout = int(sys.argv[8])

queue = json.loads(queue_path.read_text(encoding="utf-8"))
state_dir.mkdir(parents=True, exist_ok=True)

fuzz_root = state_dir / "fuzz"
fuzz_root.mkdir(parents=True, exist_ok=True)

default_seeds = [
    {"ReqData": {"ReqHeader": {"authKey": ""}, "ReqBody": {}}},
    {"ReqData": {"ReqHeader": {"authKey": "A" * 2048}, "ReqBody": {}}},
    {"ReqData": {"ReqHeader": {"authKey": "../../../etc/passwd"}, "ReqBody": {"k": "' OR 1=1 --"}}},
    {"ReqData": {"ReqHeader": {"authKey": "null"}, "ReqBody": {"nested": {"a": ["x", "y", "z"]}}}},
    {"ReqData": {"ReqHeader": {"authKey": "deadbeef"}, "ReqBody": {"blob": "X" * 4096}}},
]

def find_request_mapping(item: dict) -> str:
    if item.get("request_mapping"):
        return str(item["request_mapping"])
    src = item.get("source")
    fid = item.get("id")
    if not src or not fid:
        return ""
    try:
        data = json.loads(pathlib.Path(src).read_text(encoding="utf-8"))
    except Exception:
        return ""
    for finding in data.get("findings", []):
        if finding.get("id") == fid:
            return str(finding.get("request_mapping") or "")
    return ""

def expand_endpoints(endpoint: str):
    # Expand "/swapp/sw5/{5659,5650}" -> ["/swapp/sw5/5659", "/swapp/sw5/5650"]
    m = re.search(r"\{([^{}]+)\}", endpoint)
    if not m:
        return [endpoint]
    choices = [c.strip() for c in m.group(1).split(",") if c.strip()]
    if not choices:
        return [endpoint]
    prefix = endpoint[:m.start()]
    suffix = endpoint[m.end():]
    return [f"{prefix}{c}{suffix}" for c in choices]

def write_repro_script(path: pathlib.Path, url: str, token: str, seed_file: pathlib.Path):
    hdr = ""
    if token:
        hdr = '  -H "Authorization: Bearer $FUZZ_AUTH_TOKEN" \\\n'
    content = (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        f'curl -ksS -m {req_timeout} -i -X POST "{url}" \\\n'
        '  -H "Content-Type: application/json" \\\n'
        f"{hdr}"
        f'  --data-binary @"{seed_file}"\n'
    )
    path.write_text(content, encoding="utf-8")
    path.chmod(0o755)

run_start = time.time()
cov_outputs = []

for item in queue:
    elapsed_total = time.time() - run_start
    if elapsed_total >= max_total_sec:
        break

    cid = str(item.get("id") or uuid.uuid4())
    endpoint = find_request_mapping(item)
    if not endpoint or endpoint == "None" or "*" in endpoint:
        cov = {
            "coverage_id": str(uuid.uuid4()),
            "candidate_id": cid,
            "run_id": run_id,
            "tool": "http-fuzz-curl",
            "covered_functions_count": None,
            "covered_basic_blocks_count": None,
            "time_seconds": 0.0,
            "seed_count": 0,
            "crash": 0,
            "crash_trace": None,
            "repro_path": None,
            "status": "manual_required",
            "reason": "request_mapping missing or wildcard",
        }
        cov_path = state_dir / f"coverage_{cid}.json"
        cov_path.write_text(json.dumps(cov, ensure_ascii=False, indent=2), encoding="utf-8")
        cov_outputs.append(str(cov_path))
        continue

    endpoint_list = expand_endpoints(endpoint)
    target_urls = [f"{base_url}{ep}" for ep in endpoint_list]
    target_dir = fuzz_root / cid
    target_dir.mkdir(parents=True, exist_ok=True)

    request_log = []
    start = time.time()
    failures = []
    request_count = 0

    for url_idx, target_url in enumerate(target_urls):
        for idx, seed in enumerate(default_seeds):
            if time.time() - start >= per_target_sec:
                break
            if time.time() - run_start >= max_total_sec:
                break

            seed_path = target_dir / f"seed_{url_idx}_{idx}.json"
            resp_path = target_dir / f"response_{url_idx}_{idx}.txt"
            seed_path.write_text(json.dumps(seed, ensure_ascii=False), encoding="utf-8")

            cmd = [
                "curl", "-ksS", "-m", str(req_timeout),
                "-o", str(resp_path),
                "-w", "%{http_code} %{time_total}",
                "-X", "POST", target_url,
                "-H", "Content-Type: application/json;charset=UTF-8",
                "-H", "Cache-Control: no-cache",
            ]
            if auth_token:
                cmd += ["-H", f"Authorization: Bearer {auth_token}"]
            cmd += ["--data-binary", f"@{seed_path}"]

            t0 = time.time()
            proc = subprocess.run(cmd, capture_output=True, text=True)
            t1 = time.time()
            out = (proc.stdout or "").strip().split()
            http_code = int(out[0]) if out and out[0].isdigit() else 0

            entry = {
                "seed": str(seed_path),
                "response": str(resp_path),
                "target_url": target_url,
                "http_code": http_code,
                "exit_code": proc.returncode,
                "time_seconds": round(t1 - t0, 4),
                "stderr": (proc.stderr or "")[:4000],
                "command": " ".join(cmd),
            }
            request_log.append(entry)
            request_count += 1

            if proc.returncode != 0 or http_code >= 500:
                failures.append(entry)

    (target_dir / "requests.json").write_text(json.dumps(request_log, ensure_ascii=False, indent=2), encoding="utf-8")

    repro = None
    crash_trace = None
    if failures:
        failed = failures[0]
        repro = target_dir / "repro.sh"
        write_repro_script(repro, target_url, auth_token, pathlib.Path(failed["seed"]))
        crash_trace = f'http_code={failed["http_code"]} exit_code={failed["exit_code"]} stderr={failed["stderr"][:500]}'

    cov = {
        "coverage_id": str(uuid.uuid4()),
        "candidate_id": cid,
        "run_id": run_id,
        "tool": "http-fuzz-curl",
        "covered_functions_count": None,
        "covered_basic_blocks_count": None,
        "time_seconds": round(time.time() - start, 3),
        "seed_count": request_count,
        "crash": 1 if failures else 0,
        "crash_trace": crash_trace,
        "repro_path": str(repro) if repro else None,
        "target_url": target_urls[0] if target_urls else None,
        "target_urls": target_urls,
        "request_log": str(target_dir / "requests.json"),
    }
    cov_path = state_dir / f"coverage_{cid}.json"
    cov_path.write_text(json.dumps(cov, ensure_ascii=False, indent=2), encoding="utf-8")
    cov_outputs.append(str(cov_path))

for p in cov_outputs:
    print(f"cov:{p}")
PY

echo "fuzz gate done"
